---
jupyter:
  jupytext:
    formats: ipynb,Rmd
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.2'
      jupytext_version: 1.4.1
  kernelspec:
    display_name: Python 3
    language: python
    name: python3
---

```{python}
import numpy as np
import enchant
```

# Cryptography

A friend has emailed you the following text: **K]amua!kv$huvt**

She told you that her encryption algorithm works like this:

- to each ASCI value of each letter I add a *secret key* value. (note that ASCII values range from 0 to 255)
- additionally to make it more secure I add a variable (so called) _nonce_ value to each ASCII number.

The nonce start value is 0 for the first character of the message. For each following character I increase the nonce by 1, e.g. for the second letter the nonce added is 1, for the third letter it is 2 and so on.

`` encoded_character[i] = character[i] + key + nonce(i)``

## Assignment 2

**2.1** Is this symmetric or asymmetric encryption and explain why?

The encryption is symmetric by definition: in fact, the same key is used to encrypt and decrypt the message.

**2.2** Write a small brute force program which tests keys from $0 \dots 255$ and use a dictionary approach to figure out the original message. What is the decryption algorithm/formula to be used?

```{python}
message       = "K]amua!kv$huvt"

nonce         = np.arange(0, len(message), dtype=int)
ascii_message = np.array([ord(c) for c in message])
     
print(message)
print(ascii_message)
```

```{python}
for i in range(256):
    
    decrypt = ascii_message - i - nonce
    decrypt[decrypt < 0] = decrypt[decrypt < 0] + 256
    
    print("Key value:", i, "=>", ''.join(map(chr,decrypt)))
```

By manually looking at all the results, one obtain that the encrypted message is **Padova is cool** and that the secret key is $251$.

To authomatically detect the secret message, one could rely on the *dictionary approach*, as reported below:

```{python}
eng = enchant.Dict("en_US")

for i in range(256):
    
    decrypt = ascii_message - i - nonce
    decrypt[decrypt < 0] = decrypt[decrypt < 0] + 256
    
    decr_mess = ''.join(map(chr,decrypt))
    
    string_mess = decr_mess.split()
    mask = []
    
    for c in range(len(string_mess)):
        try:
            mask.append(eng.check(string_mess[c]))
        except:
            continue
    
    if True in mask :
        print("Key value:", i, "=>", decr_mess)
```

```{python}

```
